package com.example.store.enums;

public enum EventType {
    INVENTORY_OUT_OF_STOCK,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    SHIPPING_FAILED,
    ORDER_SHIPPED,
    ORDER_NOT_SHIPPED,
    NOTHING_TO_RELEASE,
    NOTHING_TO_REFUND,
    ALREADY_RELEASED,
    ALREADY_REFUNDED,
    ALREADY_CANCELLED,
    BANK_API_TIMEOUT,
    EMAIL_FAILED,
    EMAIL_SENT,
    CANCELLED_BY_USER,
    CANCELLATION_REJECTED,
    CANCELLATION_IN_PROGRESS,
    LOST_IN_DELIVERY
}
