package com.example.store.enums;

public enum EventType {
    INVENTORY_OUT_OF_STOCK,
    PAYMENT_FAILED,
    SHIPPING_FAILED,
    ORDER_SHIPPED,
    ORDER_NOT_SHIPPED,
    NOTHING_TO_RELEASE,
    ALREADY_RELEASED,
    EMAIL_FAILED,
    EMAIL_SENT,
    CANCELLED_BY_USER
}
