package com.example.store.enums;

public enum EventType {
    ORDER_PLACED,
    ORDER_CANCELLED,
    INVENTORY_RESERVED,
    INVENTORY_OUT_OF_STOCK,
    INVENTORY_RELEASED,
    PAYMENT_PROCESSED,
    REFUND_PROCESSED,
    SHIPMENT_CREATED,
    SHIPMENT_FAILED,
    EMAIL_SENT,
    EMAIL_FAILED
}